import { NextPage } from "next";
import Head from "next/head";
import Navbar from "../../../../../components/layout/navbar";
import Footer from "../../../../../components/layout/arpa_footer";
import SpecificSubject from "../../../../../components/layout/home/specificSubject";

const Turmas: NextPage = () => {
  const data = [
    {
      materia: "filosofia",
      contetudos: [
        {
          nome: "avaliação Especial",
          link: "https://google.drive.com/hcuiywefUnfviwd92",
        },
        {
          nome: "Trimestral",
          link: "https://google.drive.com/hcuiywefUnfviwd92",
        },
      ],
    },
    {
      materia: "português",
      contetudos: [
        {
          nome: "avaliação Especial",
          link: "https://google.drive.com/hcuiywefUnfviwd92",
        },
        {
          nome: "Trimestral",
          link: "https://google.drive.com/hcuiywefUnfviwd92",
        },
        {
          nome: "Trimestral 2",
          link: "https://google.drive.com/hcuiywefUnfviwd92",
        },
        {
          nome: "Trimestral 3",
          link: "https://google.drive.com/hcuiywefUnfviwd92",
        },
      ],
    },
    {
      materia: "História",
      contetudos: [
        {
          nome: "avaliação Especial",
          link: "https://google.drive.com/hcuiywefUnfviwd92",
        },
        {
          nome: "Trimestral",
          link: "https://google.drive.com/hcuiywefUnfviwd92",
        },
        {
          nome: "Trimestral 2",
          link: "https://google.drive.com/hcuiywefUnfviwd92",
        },
        {
          nome: "Trimestral 3",
          link: "https://google.drive.com/hcuiywefUnfviwd92",
        },
      ],
    },
  ];
  return (
    <>
      <Head>
        <title>Arpa</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Navbar />
      <main className="mt-[50px] lg:mt-[70px]">
        <div className="contentDisplay flex flex-col justify-center items-center h-auto mb-[200px] xl:mx-[100px]">
          <div className="titleForm w-full px-[20px]">
            <h2 className="text-4xl sm:text-5xl font-bold text-[#153046] text-center">
              Confira nossos resumos
            </h2>
            <h3 className="mt-5 mb-5 text-xs sm:text-sm font-medium text-[#153046] text-center">
              Aqui você tem fácil acesso aos resumos de todos os trimestres do
              ano!!!
              <br />
              Selecione sua série e comece os estudos
            </h3>
          </div>
          <div className="searchForForm mb-[50px] sm:mb-[80px] px-[20px] sm:px-[50px] xl:px-0 w-full flex flex-row justify-center items-center gap-[15px]">
            <hr className="w-full h-[5px] bg-gradient-to-r from-[#152F47] to-[#185b9600] rounded-full sm:h-[7px]" />

            <div className="inputForm w-auto">
              <select className="focus:outline-[#87abd5] w-auto py-[10px] px-[20px] sm:py-[20px] sm:px-[40px] rounded-full bg-white shadow-lg appearance-none font-semibold text-md text-[#153046]">
                <option className="bg-white rounded-xl">2023</option>
                <option className="bg-white rounded-xl">2022</option>
                <option className="bg-white rounded-xl">2021</option>
                <option className="bg-white rounded-xl">2020</option>
                <option className="bg-white rounded-xl">2019</option>
                <option className="bg-white rounded-xl">2018</option>
              </select>
            </div>
          </div>
          {data.map((dataMateria) => (
            <SpecificSubject
              materia={dataMateria.materia}
              conteudos={dataMateria.contetudos}
            />
          ))}
        </div>
      </main>
      <Footer />
    </>
  );
};
export default Turmas;
