import { NextPage } from "next";
import Head from "next/head";

import Navbar from "../components/layout/navbar";

const Contact: NextPage = () => {
  return (
    <>
      <Head>
        <title>Arpa</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Navbar />
      <main className="mt-[70px]"></main>
    </>
  );
};
export default Contact;
