import { NextPage } from "next";
import Head from "next/head";
import MediaButton from "../components/layout/home/media_button";
import Navbar from "../components/layout/navbar";
import Footer from "../components/layout/arpa_footer";
import BlueButton from "../components/layout/blue_button";

const Contact: NextPage = () => {
  return (
    <>
      <Head>
        <title>Arpa</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Navbar />
      <main className="mt-[50px] lg:mt-[70px]">
        <div className="contentDisplay flex flex-col xl:flex-row justify-center h-auto mb-[200px] xl:mx-[100px] xl:justify-start">
          <div className="leftSideContent flex flex-col items-center lg:min-w-[700px] mx-[50px]">
            <div className="titleForm w-full">
              <h2 className="text-5xl font-bold text-[#153046] text-center">
                Fale Conosco
              </h2>
              <h3 className="mt-5 mb-10 text-sm font-medium text-[#153046] text-center">
                Tem Alguma dúvida, crítica ou sugestão?
                <br />
                Preencha o formulário abaixo, responderemos o mais rápido
                possível
              </h3>
            </div>
            <div className="mainForm w-full flex flex-col items-center">
              <div className="rowForm w-full flex flex-row items-center justify-between gap-[30px]">
                <div className="inputForm w-full">
                  <h4 className="text-xl font-semibold text-[#153046]">Nome</h4>
                  <input
                    className="focus:outline-[#87abd5] w-full p-[20px] rounded-full bg-white shadow-lg my-5"
                    type="text"
                    placeholder="Ex: Felipe"
                  />
                </div>
                <div className="inputForm w-auto">
                  <h4 className="text-xl font-semibold text-[#153046]">
                    Série
                  </h4>
                  <select className="focus:outline-[#87abd5] w-auto p-[20px] rounded-full bg-white shadow-lg my-5 appearance-none font-normal text-md text-[#153046]">
                    <option className="bg-white rounded-xl">9°EF</option>
                    <option className="bg-white rounded-xl">1°EM</option>
                    <option className="bg-white rounded-xl">2°EM</option>
                    <option className="bg-white rounded-xl">3°EM</option>
                  </select>
                </div>
              </div>
              <div className="rowForm w-full">
                <div className="inputForm w-full">
                  <h4 className="text-xl font-semibold text-[#153046]">
                    E-mail *
                  </h4>
                  <input
                    className="focus:outline-[#87abd5] w-full p-[20px] rounded-full bg-white shadow-lg my-5"
                    type="text"
                    placeholder="axxxxxx@alunos.colband.com.br"
                  />
                </div>
              </div>
              <div className="rowForm w-full">
                <div className="inputForm w-full">
                  <h4 className="text-xl font-semibold text-[#153046]">
                    Assunto ou Disciplina *
                  </h4>
                  <input
                    className="focus:outline-[#87abd5] w-full p-[20px] rounded-full bg-white shadow-lg my-5"
                    type="text"
                    placeholder="Ex.: Biologia/Artrópodes"
                  />
                </div>
              </div>
              <div className="rowForm w-full">
                <div className="inputForm w-full">
                  <h4 className="text-xl font-semibold text-[#153046]">
                    Dúvida ou Sugestão
                  </h4>
                  <textarea
                    className="focus:outline-[#87abd5] w-full p-[20px] rounded-2xl bg-white shadow-lg my-5"
                    placeholder="Escreva sua dúvida ou sugestão aqui..."
                  />
                </div>
              </div>
              <BlueButton
                text="Enviar"
                paddingX="100px"
                paddingY="20px"
                fontWeight="600"
                fontSize="xl"
                mt="20px"
              />
            </div>
          </div>
          <div className="rightSideDisplay w-full flex flex-col items-center">
            <img
              src="email_us_mobile.svg"
              alt=""
              className="flex lg:hidden min-w-[250px] sm:min-w-[400px] mt-[100px]"
            />
            <img
              src="email_us_desktop.svg"
              alt=""
              className="hidden lg:block w-[500px] mt-[100px] xl:mt-[0px]"
            />
            <div className="buttonsRightSide flex justify-center items-center gap-5 mt-[30px]">
              <MediaButton
                number={2}
                link={""}
                size={"text-[40px]"}
                padding={"p-[20px] sm:p-[25px]"}
                rounded={"rounded-full sm:rounded-[40px]"}
              />
              <MediaButton
                number={1}
                link={"https://www.instagram.com/arpa3band/"}
                size={"text-[40px]"}
                padding={"p-[20px] sm:p-[25px]"}
              />
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};
export default Contact;
