import { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/layout/navbar";
import Footer from "../components/layout/arpa_footer";
import BlueButton from "../components/layout/blue_button";
import Term from "../components/layout/home/especificTerm";

const Summaries: NextPage = () => {
  return (
    <>
      <Head>
        <title>Arpa</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Navbar />
      <main className="mt-[50px] lg:mt-[70px]">
        <div className="contentDisplay flex flex-col justify-center h-auto mb-[200px] xl:mx-[100px] xl:justify-start">
          <div className="titleForm w-full">
            <h2 className="text-5xl font-bold text-[#153046] text-center">
              Confira nossos resumos
            </h2>
            <h3 className="mt-5 mb-10 text-sm font-medium text-[#153046] text-center">
              Aqui você tem fácil acesso aos resumos de todos os trimestres do
              ano!!!
              <br />
              Selecione sua série e comece os estudos
            </h3>
          </div>
          <div className="searchForForm w-[90%] flex flex-row justify-center items-center">
            <div className="rowForm w-full flex flex-row items-center justify-center gap-[15px]">
              <hr className="my-[20px] w-full h-[5px] bg-gradient-to-r from-[#152F47] to-[#185b9600] rounded-full sm:h-[7px]" />

              <div className="inputForm w-auto">
                <select className="focus:outline-[#87abd5] w-auto py-[10px] px-[20px] sm:py-[20px] sm:px-[40px] rounded-full bg-white shadow-lg my-5 appearance-none font-semibold text-md text-[#153046]">
                  <option className="bg-white rounded-xl">2023</option>
                  <option className="bg-white rounded-xl">2022</option>
                  <option className="bg-white rounded-xl">2021</option>
                  <option className="bg-white rounded-xl">2020</option>
                  <option className="bg-white rounded-xl">2019</option>
                  <option className="bg-white rounded-xl">2018</option>
                </select>
              </div>

              <div className="inputForm w-auto">
                <select className="focus:outline-[#87abd5] w-auto py-[10px] px-[20px] sm:py-[20px] sm:px-[40px] rounded-full bg-white shadow-lg my-5 appearance-none font-semibold text-md text-[#153046]">
                  <option className="bg-white rounded-xl">9°EF</option>
                  <option className="bg-white rounded-xl">1°EM</option>
                  <option className="bg-white rounded-xl">2°EM</option>
                  <option className="bg-white rounded-xl">3°EM</option>
                </select>
              </div>
            </div>
          </div>
          <div className="searchForForm w-full flex flex-col items-center gap-[30px]">
            <Term
              text={"1ºTri"}
              rounded={"50px"}
              boxSize={"250px"}
              textColor={"#000000"}
            />
            <Term
              text={"2ºTri"}
              rounded={"50px"}
              boxSize={"250px"}
              textColor={"#000000"}
            />
            <Term
              text={"3ºTri"}
              rounded={"50px"}
              boxSize={"250px"}
              textColor={"#000000"}
            />
          </div>

          <BlueButton
            text="Enviar"
            paddingX="100px"
            paddingY="20px"
            fontWeight="600"
            fontSize="xl"
            mt="20px"
          />
        </div>
      </main>
      <Footer />
    </>
  );
};
export default Summaries;
